### ISSUE TITLE
The merge from Kaolin makes some

### ISSUE THREAD

**Issue by SophusDavid** [nv-tlabs/FlexiCubes#10]

**Comment by MHassan1122** [comment]
same problem raised as you mentioned.

Traceback (most recent call last):
  File "C:\Users\admin\FlexiCubes-main\examples\optimize.py", line 88, in <module>
    mv, mvp = render.get_random_camera_batch(FLAGS.batch, iter_res=FLAGS.train_res, device=device)
ValueError: too many values to unpack (expected 2)

**Comment by SophusDavid** [comment]
> same problem raised as you mentioned.
> 
> Traceback (most recent call last): File "C:\Users\admin\FlexiCubes-main\examples\optimize.py", line 88, in mv, mvp = render.get_random_camera_batch(FLAGS.batch, iter_res=FLAGS.train_res, device=device) ValueError: too many values to unpack (expected 2)

I can share my solution:
follow the README.md in the latest commit  to install Flexicubes:
```
conda create -n flexicubes python=3.9
conda activate flexicubes
conda install pytorch==1.12.0 torchvision==0.13.0 torchaudio==0.12.0 cudatoolkit=11.3 -c pytorch
pip install imageio trimesh tqdm matplotlib torch_scatter ninja
pip install git+https://github.com/NVlabs/nvdiffrast/
pip install kaolin==0.15.0 -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-1.12.0_cu113.html

```
check out the git branch to previous commit . 
`git checkout HEAD^`
reinstall Kaolin :
`pip install kaolin==0.13.0 -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-1.12.0_cu113.html`

**Comment by SophusDavid** [comment]
> can you explain me in details. I followed your instructions but it seem the same problem again. thanks for you time and kind assistance.

![image](https://github.com/nv-tlabs/FlexiCubes/assets/130123455/4eadc0ee-d663-48e9-9555-c98991952127)

i followed the command lines above and it worked .

the key point is that  the latest version of flexicubes uses kaolin 15 but not adapt their code to kaolin 15's api .so you need to change to previous version(```git checkout HEAD^```)
Then you should to install the previous kaolin 
(```pip install kaolin==0.13.0 -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-1.12.0_{your cuda version}.html ```)
and version of my cuda is 11.3 so i install 
```pip install kaolin==0.13.0 -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-1.12.0_cu113.html ```

hope this will work for you.

**Comment by MHassan1122** [comment]
Looking in links: https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-1.12.1_cu113.html
ERROR: Could not find a version that satisfies the requirement kaolin==0.13.0 (from versions: 0.1, 0.14.0, 0.15.0)
ERROR: No matching distribution found for kaolin==0.13.0

**Comment by MHassan1122** [comment]
Dear @SophusDavid 
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\admin\anaconda3\envs\flexicube\lib\site-packages (from Jinja2>=3.0->flask==2.0.3->kaolin==0.13.0) (2.1.4)
when i tried many times even with others version as well but all is vain. 
the same error
(flexicube) C:\Users\admin\FlexiCubes-main\examples>python optimize.py --ref_mesh data/inputmodels/block.obj --out_dir out/block
Traceback (most recent call last):
  File "C:\Users\admin\FlexiCubes-main\examples\optimize.py", line 88, in <module>
    mv, mvp = render.get_random_camera_batch(FLAGS.batch, iter_res=FLAGS.train_res, device=device)
ValueError: too many values to unpack (expected 2)

**Comment by frankshen07** [comment]
Apologies for the issues caused by the Kaolin merge. I've added back the previous functions we used to produce the paper's results, which do not depend on Kaolin. The error should be resolved now with the latest commit.
