### ISSUE TITLE
some issues during implementation.

### ISSUE THREAD

**Issue by MHassan1122** [nv-tlabs/FlexiCubes#11]
when i want to run the program show the following error, anyone who has experienced in this , I try my best and check the method in render.py as well. 

Traceback (most recent call last):
  File "C:\Users\admin\FlexiCubes-main\examples\optimize.py", line 88, in <module>
    mv, mvp = render.get_random_camera_batch(FLAGS.batch, iter_res=FLAGS.train_res, device=device)
ValueError: too many values to unpack (expected 2)

**Comment by SophusDavid** [comment]
use previous commit 
#10

**Comment by MHassan1122** [comment]
@SophusDavid 
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\admin\anaconda3\envs\flexicube\lib\site-packages (from Jinja2>=3.0->flask==2.0.3->kaolin==0.13.0) (2.1.4)
(flexicube) C:\Users\admin\FlexiCubes\examples>python optimize.py --ref_mesh data/inputmodels/block.obj --out_dir out/block
Traceback (most recent call last):
  File "C:\Users\admin\FlexiCubes\examples\optimize.py", line 88, in <module>
    mv, mvp = render.get_random_camera_batch(FLAGS.batch, iter_res=FLAGS.train_res, device=device)
ValueError: too many values to unpack (expected 2)

can you tell me what will be the solution

**Comment by frankshen07** [comment]
Apologies for the issues caused by the Kaolin merge. I've added back the previous functions we used to produce the paper's results, which do not depend on Kaolin. The error should be resolved now with the latest commit.
