### ISSUE TITLE
issues during implementation 

### ISSUE THREAD

**Issue by MHassan1122** [nv-tlabs/FlexiCubes#13]
Hi dear @frankshen07  hope you will be in good health.
  i tried my best to employ this amazing project but stuck in one step as you can see the  following error
  (flexicube) C:\Users\admin\FlexiCubes\examples>python optimize.py --ref_mesh data/inputmodels/block.obj --out_dir out/block
Traceback (most recent call last):
  File "C:\Users\admin\FlexiCubes\examples\optimize.py", line 88, in <module>
    mv, mvp = render.get_random_camera_batch(FLAGS.batch, iter_res=FLAGS.train_res, device=device)
ValueError: too many values to unpack (expected 2)

i tried with different version of kaolin=0.13.0 but not a able to tacke this issue. I use window 10 with RTXGEFORCE.
another question is that can we use this for single view reconstruction purpose. Is it possible or not.

**Comment by frankshen07** [comment]
Apologies for the issues caused by the Kaolin merge. I've added back the previous functions we used to produce the paper's results, which do not depend on Kaolin. The error should be resolved now with the latest commit.

Re. single-view reconstruction, our code only supports multi-view reconstruction.

**Comment by MHassan1122** [comment]
@frankshen07 Thanks for your response. as you mentioned that there is no depend on Koalin.
i used the optimization.ipynb for implementation, when I run cell 6, errors are occured which is related to **nvdiffrast** as you can know that you import nvdiffrast in render.py like 
**import nvdiffrast.torch as dr**
Here is the attached file for your evaluation.
![cuda error](https://github.com/nv-tlabs/FlexiCubes/assets/125865702/9b9eed13-ab28-427a-880f-baef2904dd63)

**Comment by MHassan1122** [comment]
I also tried to run in prompt according to given instruction but same error as arise in the optimization.ipynb 

(flexicube) C:\Users\admin\FlexiCubes\examples>python optimize.py --ref_mesh data/inputmodels/block.obj --out_dir out/block
Traceback (most recent call last):
  File "C:\Users\admin\FlexiCubes\examples\optimize.py", line 90, in <module>
    target = render.render_mesh_paper(gt_mesh, mv, mvp, FLAGS.train_res)
  File "C:\Users\admin\FlexiCubes\examples\render.py", line 124, in render_mesh_paper
    rast, db = dr.rasterize(
  File "C:\Users\admin\anaconda3\envs\flexicube\lib\site-packages\nvdiffrast\torch\ops.py", line 310, in rasterize
    return _rasterize_func.apply(glctx, pos, tri, resolution, ranges, grad_db, -1)
  File "C:\Users\admin\anaconda3\envs\flexicube\lib\site-packages\nvdiffrast\torch\ops.py", line 246, in forward
    out, out_db = _get_plugin(gl=True).rasterize_fwd_gl(raster_ctx.cpp_wrapper, pos, tri, resolution, ranges, peeling_idx)
RuntimeError: Cuda error: 304[cudaGraphicsGLRegisterBuffer(&s.cudaPosBuffer, s.glPosBuffer, cudaGraphicsRegisterFlagsWriteDiscard);]
